import streamlit as st
import pandas as pd

from joblib import load

# MUST be the first Streamlit command
st.set_page_config(
    page_title="Heart Disease Predictor",
    layout="wide"
)

MODEL_PATH = (
    "outputs/models/"
    "random_forest.pkl"
)

model = load(MODEL_PATH)

st.title(
    "Heart Disease Risk Prediction"
)

st.info(
"""
This application predicts the probability of heart disease using a Random Forest model trained on the UCI Heart Disease dataset.

Output:
- Probability Score
- Predicted Class
- Risk Category

This tool is for educational purposes only and not a medical diagnosis.
"""
)

st.write(
    """
Predict heart disease risk using the trained Random Forest model.
"""
)

col1, col2 = st.columns(2)

with col1:

    age = st.number_input(
        "Age",
        min_value=18,
        max_value=100,
        value=50,
        help="Patient age in years"
    )

    sex_options = {
        "Female": 0,
        "Male": 1
    }

    sex_label = st.selectbox(
        "Sex",
        list(sex_options.keys())
    )

    sex = sex_options[sex_label]

    cp_options = {
        "Typical Angina": 0,
        "Atypical Angina": 1,
        "Non-Anginal Pain": 2,
        "Asymptomatic": 3
    }

    cp_label = st.selectbox(
        "Chest Pain Type",
        list(cp_options.keys())
    )

    cp = cp_options[cp_label]

    trestbps = st.number_input(
        "Resting Blood Pressure",
        value=120,
        help="Resting blood pressure in mm Hg"
    )

    chol = st.number_input(
        "Cholesterol",
        value=200,
        help="Serum cholesterol in mg/dl"
    )

    fbs_options = {
        "≤ 120 mg/dl": 0,
        "> 120 mg/dl": 1
    }

    fbs_label = st.selectbox(
        "Fasting Blood Sugar",
        list(fbs_options.keys())
    )

    fbs = fbs_options[fbs_label]

    restecg_options = {
        "Normal": 0,
        "ST-T Wave Abnormality": 1,
        "Left Ventricular Hypertrophy": 2
    }

    restecg_label = st.selectbox(
        "Resting ECG Result",
        list(restecg_options.keys())
    )

    restecg = restecg_options[restecg_label]

with col2:

    thalach = st.number_input(
        "Maximum Heart Rate Achieved",
        value=150
    )

    exang_options = {
        "No": 0,
        "Yes": 1
    }

    exang_label = st.selectbox(
        "Exercise Induced Angina",
        list(exang_options.keys())
    )

    exang = exang_options[exang_label]

    oldpeak = st.number_input(
        "Old Peak",
        value=1.0,
        help="ST depression induced by exercise relative to rest"
    )

    slope_options = {
        "Upsloping": 0,
        "Flat": 1,
        "Downsloping": 2
    }

    slope_label = st.selectbox(
        "ST Segment Slope",
        list(slope_options.keys())
    )

    slope = slope_options[slope_label]

    ca = st.selectbox(
        "Number of Major Vessels",
        [0, 1, 2, 3]
    )

    thal_options = {
        "Normal": 0,
        "Fixed Defect": 1,
        "Reversible Defect": 2
    }

    thal_label = st.selectbox(
        "Thalassemia Test Result",
        list(thal_options.keys())
    )

    thal = thal_options[thal_label]

if st.button("Predict"):

    input_df = pd.DataFrame(
        [[
            age,
            sex,
            cp,
            trestbps,
            chol,
            fbs,
            restecg,
            thalach,
            exang,
            oldpeak,
            slope,
            ca,
            thal
        ]],
        columns=[
            "age",
            "sex",
            "cp",
            "trestbps",
            "chol",
            "fbs",
            "restecg",
            "thalach",
            "exang",
            "oldpeak",
            "slope",
            "ca",
            "thal"
        ]
    )

    probability = model.predict_proba(input_df)[0][1]

    prediction = model.predict(input_df)[0]

    st.subheader("Prediction Results")

    st.metric(
        "Heart Disease Probability",
        f"{probability:.2%}"
    )

    st.metric(
        "Predicted Class",
        int(prediction)
    )

    if probability >= 0.70:

        st.error(
            "High Risk of Heart Disease"
        )

    elif probability >= 0.40:

        st.warning(
            "Moderate Risk of Heart Disease"
        )

    else:

        st.success(
            "Low Risk of Heart Disease"
        )

    st.write("---")

    st.write(
        f"""
### Interpretation

- Probability Score: **{probability:.2%}**
- Prediction: **{"Heart Disease Detected" if prediction == 1 else "No Heart Disease Detected"}**

Note: This prediction is generated by a machine learning model and should not be used as a substitute for professional medical advice.
"""
    )